import ModifiedCartan.ScalarProximityMultiplicities
import ModifiedCartan.ScalarDeficiencyQuantization
import ModifiedCartan.ScalarTheoremA
import ModifiedCartan.ScalarLinearTargetClassification
import ModifiedCartan.ScalarTargetMatrixEquiv
import ModifiedCartan.ScalarProximityMatrixGauge
import ModifiedCartan.ScalarDyadicProximityLimit
import ModifiedCartan.ScalarSectorArcs
import ModifiedCartan.ScalarSectorIntegrals
import ModifiedCartan.ScalarSectorMeanDefect
import ModifiedCartan.ScalarDyadicMeanDefect
import ModifiedCartan.ScalarProximityPair
import ModifiedCartan.ScalarProximityMean
import ModifiedCartan.ScalarProximityComparison
import ModifiedCartan.ScalarProximityLimits
import ModifiedCartan.ScalarActualTargetCircleLimits
import ModifiedCartan.ScalarTargetGaugeMean
import ModifiedCartan.ScalarProjectiveProximityLimits
import ModifiedCartan.AnalyticLogRadialIntegral
import ModifiedCartan.AnalyticLogCircleLimits
import ModifiedCartan.AnalyticLogCircleMean
import ModifiedCartan.AnalyticLogApproximation
import ModifiedCartan.ScalarActualTargetBasics
import ModifiedCartan.ScalarActualTargetLimits
import ModifiedCartan.ExponentialLogMargin
import ModifiedCartan.AnalyticLogMeasureUpgrade
import ModifiedCartan.ScalarTargetPairMax
import ModifiedCartan.ScalarOtherTargetSector
import ModifiedCartan.ScalarTargetLogData
import ModifiedCartan.ScalarTargetSectorIdentity
import ModifiedCartan.ScalarDistinctTargetBounds
import ModifiedCartan.TwoPhaseSmoothPatches
import ModifiedCartan.ScalarNegativeTargetSector
import ModifiedCartan.ScalarComparablePeakLimits
import ModifiedCartan.ScalarSmoothNegativeTarget
import ModifiedCartan.ScalarTargetHorizontalCaps
import ModifiedCartan.ScalarSmoothTargetBound
import ModifiedCartan.ActualNormUpper
import ModifiedCartan.ScalarTargetUnitary
import ModifiedCartan.ArbitraryRadiusAccuracy
import ModifiedCartan.PolynomialCrossingCap
import ModifiedCartan.ScalarTargetPolynomialBounds
import ModifiedCartan.ScalarUnitaryJetLower
import ModifiedCartan.JetLowerCompactness
import ModifiedCartan.ScalarPrescribedUnitaryLimits
import ModifiedCartan.ScalarHorizontalRescale
import ModifiedCartan.ScalarSharpComparableLines
import ModifiedCartan.ScalarDyadicTargetRates
import ModifiedCartan.ScalarSharpLocalTargetLines
import ModifiedCartan.ScalarSharpRadiusTransfer
import ModifiedCartan.ScalarSharpPrescribedWidth
import ModifiedCartan.ScalarTargetLinearBounds
import ModifiedCartan.ScalarSharpTargetPropagation
import ModifiedCartan.ScalarLevelChartCompact
import ModifiedCartan.ScalarLevelChartDilation
import ModifiedCartan.ScalarFarDyadicTargets
import ModifiedCartan.ScalarFixedRateMovingAnchors
import ModifiedCartan.ScalarFixedRateMovingConnections
import ModifiedCartan.ScalarSharpScaleBounds
import ModifiedCartan.ScalarFixedRateCrosses
import ModifiedCartan.ScalarFixedRateConnections
import ModifiedCartan.ScalarLevelChart
import ModifiedCartan.ScalarSharpLevelCrosses
import ModifiedCartan.ScalarPhaseSharpCrosses
import ModifiedCartan.ScalarComparableLineTargets
import ModifiedCartan.ScalarArbitraryRadiusTargets
import ModifiedCartan.ScalarRadiusSectorTargets
import ModifiedCartan.ScalarComparableHorizontalLines
import ModifiedCartan.ScalarDyadicCeilingLines
import ModifiedCartan.ScalarComparableTargetBridge
import ModifiedCartan.ScalarComparableFixedTarget
import ModifiedCartan.ScalarComparablePeaks
import ModifiedCartan.ScalarScaledLines
import ModifiedCartan.ScalarDyadicDecomposition
import ModifiedCartan.ScalarScaledHorizontalBounds
import ModifiedCartan.CharacteristicComparableBounds
import ModifiedCartan.ScalarDyadicLineTargets
import ModifiedCartan.ScalarDyadicTargetUniqueness
import ModifiedCartan.ScalarDyadicTargetRefinement
import ModifiedCartan.ScalarVariableAnchors
import ModifiedCartan.ScalarVariableConnections
import ModifiedCartan.ScalarSharpSpeed
import ModifiedCartan.ScalarSharpCrosses
import ModifiedCartan.ScalarRadialPeakDisks
import ModifiedCartan.ScalarExponentialBounds
import ModifiedCartan.ScalarMovingLines
import ModifiedCartan.ScalarMovingConnections
import ModifiedCartan.ScalarDyadicAnchorSteps
import ModifiedCartan.ScalarEventualGluing
import ModifiedCartan.ScalarDyadicTargets
import ModifiedCartan.ScalarDyadicSectorTargets
import ModifiedCartan.ScalarPeakDisks
import ModifiedCartan.ScalarMovingCrosses
import ModifiedCartan.PositiveRateCompactness
import ModifiedCartan.ScalarUniformPeakCrosses
import ModifiedCartan.ScalarMovingAnchors
import ModifiedCartan.ScalarPhaseIsometry
import ModifiedCartan.ScalarPhaseCrosses
import ModifiedCartan.ScalarPhaseUniformity
import ModifiedCartan.ScalarPhasePeakLimits
import ModifiedCartan.ScalarPhaseChoice
import ModifiedCartan.ScalarPhaseApproximation
import ModifiedCartan.ScalarPhaseSlowChange
import ModifiedCartan.ScalarRootCorrection
import ModifiedCartan.ScalarPeakTracking
import ModifiedCartan.ScalarQuadraticProfile
import ModifiedCartan.ScalarProfileUniqueness
import ModifiedCartan.ScalarProfileContinuity
import ModifiedCartan.ScalarProfileCompactness
import ModifiedCartan.ScalarSphereIsometry
import ModifiedCartan.ScalarPotentialSlowChange
import ModifiedCartan.ScalarComparableLimits
import ModifiedCartan.ScalarComparableBounded
import ModifiedCartan.VariableDilation
import ModifiedCartan.VariableScaling
import ModifiedCartan.ScalarSpherePotential
import ModifiedCartan.LocalLpEventualEquality
import ModifiedCartan.ScalarSpherePotentialLimit
import ModifiedCartan.ScalarSectorMultiplicity
import ModifiedCartan.ScalarSectorData
import ModifiedCartan.ScalarFiniteTargets
import ModifiedCartan.ScalarFinitePeakTargets
import ModifiedCartan.ArbitraryRadiusReindex
import ModifiedCartan.ScalarSectorRoots
import ModifiedCartan.ScalarSectorGeometry
import ModifiedCartan.ScalarSectorCover
import ModifiedCartan.ScalarPeakDirections
import ModifiedCartan.ScalarPeakChart
import ModifiedCartan.ScalarGeometricTarget
import ModifiedCartan.ScalarTargetOverlap
import ModifiedCartan.ScalarChartDominance
import ModifiedCartan.ScalarChartTarget
import ModifiedCartan.ScalarActualChartTarget
import ModifiedCartan.ScalarAnchorExponential
import ModifiedCartan.ScalarHorizontalSelection
import ModifiedCartan.ScalarRectangleCrosses
import ModifiedCartan.ScalarAdjacentAnchors
import ModifiedCartan.RectangleBridge
import ModifiedCartan.ComplexRect
import ModifiedCartan.ScalarValueGluing
import ModifiedCartan.ScalarScaleSeparation
import ModifiedCartan.RectangleConnectivity
import ModifiedCartan.ScalarPositiveCenters
import ModifiedCartan.ScalarCrossDiameter
import ModifiedCartan.ScalarChartPaths
import ModifiedCartan.ScalarPositiveChart
import ModifiedCartan.ScalarSectorComponent
import ModifiedCartan.ConvexAffineContact
import ModifiedCartan.ScalarPowerChartProfile
import ModifiedCartan.ScalarPowerDomain
import ModifiedCartan.ScalarSphericalLine
import ModifiedCartan.ScalarGoodCross
import ModifiedCartan.ScalarDominantComponent
import ModifiedCartan.ScalarNormSmooth
import ModifiedCartan.PolynomialVerticalLine
import ModifiedCartan.PolynomialGaugeLower
import ModifiedCartan.ComplexRectangleIntegral
import ModifiedCartan.PolynomialGoodLineLimit
import ModifiedCartan.GoodLineIntegral
import ModifiedCartan.GoodLineSelection
import ModifiedCartan.LogNormPathDerivative
import ModifiedCartan.LogNormLineEstimate
import ModifiedCartan.PolynomialGoodLine
import ModifiedCartan.ScalarSphereValues
import ModifiedCartan.ScalarSphericalDecay
import ModifiedCartan.ScalarSphereProjection
import ModifiedCartan.ScalarSphericalSpeed
import ModifiedCartan.ScalarNormPowerProfile
import ModifiedCartan.ScalarCosineIntegral
import ModifiedCartan.ScalarPowerPolar
import ModifiedCartan.ScalarNormNormalizedProfile
import ModifiedCartan.TwoPhaseForms
import ModifiedCartan.TwoPhaseHomogeneous
import ModifiedCartan.ScalarNormTwoPhase
import ModifiedCartan.ScalarNormLocalAbsolute
import ModifiedCartan.ScalarNormSquare
import ModifiedCartan.LocalAffineMaximum
import ModifiedCartan.TwoPhaseLocalForm
import ModifiedCartan.UnitaryPowerGradient
import ModifiedCartan.ScalarPowerGradient
import ModifiedCartan.ScalarValueCharacteristic
import ModifiedCartan.ScalarDeficiencyBasics
import ModifiedCartan.BoundedGrowthTransfer
import ModifiedCartan.ScalarTheoremGrowth
import ModifiedCartan.GlobalMeromorphicPair
import ModifiedCartan.ScalarDefinitions
import ModifiedCartan.ScalarCurveLift
import ModifiedCartan.ScalarRamificationBridge
import ModifiedCartan.ScalarCharacteristicBridge
import ModifiedCartan.CorrectedLinearFactor
import ModifiedCartan.CorrectedDivisorFactor
import ModifiedCartan.DivisorCopies
import ModifiedCartan.DivisorEntireProduct
import ModifiedCartan.DivisorEntireMultiplicity
import ModifiedCartan.NHElementaryBounds
import ModifiedCartan.NHRadiusSelection
import ModifiedCartan.NHControlledRemainder
import ModifiedCartan.NHLocalDecomposition
import ModifiedCartan.NHLogDerivativeControl
import ModifiedCartan.NHHigherRatioControl
import ModifiedCartan.NHControlSize
import ModifiedCartan.NevanlinnaHiong
import ModifiedCartan.LocalKernelBounds
import ModifiedCartan.LocalPoissonRemainder
import ModifiedCartan.MeromorphicDerivativeDecomposition
import ModifiedCartan.LocalProximityArithmetic
import ModifiedCartan.LocalPairMean
import ModifiedCartan.LocalPairCharacteristic
import ModifiedCartan.CircleSingularSums
import ModifiedCartan.DiskDivisorMass
import ModifiedCartan.DiskRegularRadius
import ModifiedCartan.LocalReducedPair
import ModifiedCartan.LocalPoissonMajorant
import ModifiedCartan.SineHalfPower
import ModifiedCartan.CircleSingularHalfPower
import ModifiedCartan.DiskCharacteristic
import ModifiedCartan.DiskBoundaryMean
import ModifiedCartan.CircleMomentProximity
import ModifiedCartan.ZeroSharpWronskian
import ModifiedCartan.QuadraticLogDerivative
import ModifiedCartan.ZeroSharpCurveBounds
import ModifiedCartan.QuadraticLogLimits
import ModifiedCartan.SharpnessZero
import ModifiedCartan.EntireDerivativeNontrivial
import ModifiedCartan.ZeroSharpRealRoots
import ModifiedCartan.ZeroSharpRolle
import ModifiedCartan.FiniteRootCountingLower
import ModifiedCartan.ZeroSharpCountingLower
import ModifiedCartan.ZeroSharpMajorant
import ModifiedCartan.PolynomialCurveGrowth
import ModifiedCartan.RationalCharacteristicGrowth
import ModifiedCartan.SharpnessOrders
import ModifiedCartan.SharpnessRootIndicator
import ModifiedCartan.RootIndicatorSectors
import ModifiedCartan.RootIndicatorIntegral
import ModifiedCartan.SharpnessRayAE
import ModifiedCartan.SharpnessCharacteristicLimit
import ModifiedCartan.VectorRayGrowth
import ModifiedCartan.SharpnessRayLimit
import ModifiedCartan.SharpnessCombinations
import ModifiedCartan.RayModeRealization
import ModifiedCartan.ExponentialUpperRate
import ModifiedCartan.RayUpperPrimitives
import ModifiedCartan.ScalarRayGrowthUpper
import ModifiedCartan.WeightedPrimitive
import ModifiedCartan.PowerExpProfile
import ModifiedCartan.PowerExpPrimitive
import ModifiedCartan.RayPrimitives
import ModifiedCartan.LinearODESpan
import ModifiedCartan.RayMatrixContinuity
import ModifiedCartan.RaySolutionExpansion
import ModifiedCartan.PowerExpLog
import ModifiedCartan.RayFourierSystem
import ModifiedCartan.RayPhases
import ModifiedCartan.FirstOrderPiTail
import ModifiedCartan.RayCompanionAsymptotics
import ModifiedCartan.RayPowerClock
import ModifiedCartan.RayScaledDerivatives
import ModifiedCartan.RayScaleAlgebra
import ModifiedCartan.RayCompanionSystem
import ModifiedCartan.SharpnessFourier
import ModifiedCartan.SharpnessCompanion
import ModifiedCartan.FirstOrderGaugeAsymptotics
import ModifiedCartan.FirstOrderDiagonalTail
import ModifiedCartan.FirstOrderElimination
import ModifiedCartan.FirstOrderError
import ModifiedCartan.FirstOrderGaugeSolutions
import ModifiedCartan.DeterminantRowBounds
import ModifiedCartan.SharpnessDomination
import ModifiedCartan.ScaledJets
import ModifiedCartan.SharpnessDerivativeBounds
import ModifiedCartan.EuclideanDiagonalTail
import ModifiedCartan.LinearODEExtension
import ModifiedCartan.LinearODEIndependent
import ModifiedCartan.IntegrableSystem
import ModifiedCartan.LinearODECompact
import ModifiedCartan.DiagonalHalfLine
import ModifiedCartan.LinearPicardTerms
import ModifiedCartan.LinearPicardSolution
import ModifiedCartan.DiagonalTail
import ModifiedCartan.DiagonalTailIndependent
import ModifiedCartan.DichotomyOperator
import ModifiedCartan.DichotomyFixedPoint
import ModifiedCartan.DichotomyPrimitive
import ModifiedCartan.DichotomyKernels
import ModifiedCartan.SharpnessBaseSolutions
import ModifiedCartan.EntirePrimitives
import ModifiedCartan.SharpnessSystemExistence
import ModifiedCartan.SharpnessCoefficients
import ModifiedCartan.EntireSeries
import ModifiedCartan.ZeroSharpProduct
import ModifiedCartan.SharpnessWronskian
import ModifiedCartan.MainTheorem
import ModifiedCartan.CharacteristicRatioLimit
import ModifiedCartan.MonotoneCompactUniformity
import ModifiedCartan.RegularVariation
import ModifiedCartan.MonotoneWeightedIntegrals
import ModifiedCartan.SubsequenceRatios
import ModifiedCartan.HomogeneousRadialMeans
import ModifiedCartan.NormLogIntegrals
import ModifiedCartan.AnnularRatioLimit
import ModifiedCartan.RadialConvexBalance
import ModifiedCartan.GoodCenterHomogeneity
import ModifiedCartan.Homogeneity
import ModifiedCartan.PowerChartAnalytic
import ModifiedCartan.PowerChartGeometry
import ModifiedCartan.PowerChartCoefficients
import ModifiedCartan.UnitaryPowerConvexity
import ModifiedCartan.SmallExponentNorm
import ModifiedCartan.InversePullbackAE
import ModifiedCartan.AnalyticLogPullback
import ModifiedCartan.InversePullbackBound
import ModifiedCartan.InversePullbackConvergence
import ModifiedCartan.UnitaryComponentRegularity
import ModifiedCartan.PointwiseUnitaryBalance
import ModifiedCartan.UnitaryPolynomialCoefficients
import ModifiedCartan.UnitaryComponentGradient
import ModifiedCartan.ArbitraryPolynomialCoefficients
import ModifiedCartan.PolynomialGradientRegularity
import ModifiedCartan.NormalizedGradientEquation
import ModifiedCartan.MonicEquationBound
import ModifiedCartan.SubharmonicLocalConvexity
import ModifiedCartan.LocalMidpointMaximum
import ModifiedCartan.LocalToGlobalConvexity
import ModifiedCartan.FiniteGradientConvexity
import ModifiedCartan.GenericPhaseDirections
import ModifiedCartan.PhaseAffineMax
import ModifiedCartan.LocalPhaseMaximum
import ModifiedCartan.WeakGradientAffine
import ModifiedCartan.PhaseConeAffine
import ModifiedCartan.EssentialPhases
import ModifiedCartan.WeakGradientLocalConstancy
import ModifiedCartan.StrictPhaseCone
import ModifiedCartan.PhaseConePropagation
import ModifiedCartan.DirectionalComplexLog
import ModifiedCartan.DirectionalLogTest
import ModifiedCartan.DirectionalGradientSmoothing
import ModifiedCartan.WeakDirectionalLogTest
import ModifiedCartan.LogPhaseTest
import ModifiedCartan.DirectionalPhaseTest
import ModifiedCartan.DirectionalTestSmoothing
import ModifiedCartan.PhaseIndicator
import ModifiedCartan.PhaseCutoffMonotonicity
import ModifiedCartan.PhaseLogLimit
import ModifiedCartan.PhaseLogDominated
import ModifiedCartan.ZeroPhaseTest
import ModifiedCartan.RegularizedLogBounds
import ModifiedCartan.SubharmonicGradientSmoothing
import ModifiedCartan.WeakGradientLogTest
import ModifiedCartan.WeakGradientSmoothConvergence
import ModifiedCartan.RegularizedLogTest
import ModifiedCartan.ClassicalGradientLaplacian
import ModifiedCartan.RegularizedComplexLog
import ModifiedCartan.WeakGradientHalfPlane
import ModifiedCartan.DiskConvolutionFubini
import ModifiedCartan.SubharmonicConvolution
import ModifiedCartan.SecondOrderTaylor
import ModifiedCartan.QuadraticTrace
import ModifiedCartan.SecondOrderTaylorBound
import ModifiedCartan.QuarterMeanBound
import ModifiedCartan.DiskIsometry
import ModifiedCartan.QuarterDiskIntegral
import ModifiedCartan.SmoothSubharmonicLaplacian
import ModifiedCartan.WeakGradientLipschitz
import ModifiedCartan.SubharmonicContinuousRepresentative
import ModifiedCartan.SubharmonicLipschitz
import ModifiedCartan.WeakGradientDirectional
import ModifiedCartan.WeakGradientConvolution
import ModifiedCartan.WeakGradientSmoothBound
import ModifiedCartan.BasisAtPoint
import ModifiedCartan.GoodCenterComponentValue
import ModifiedCartan.UnitaryLogBalance
import ModifiedCartan.PointValueUpper
import ModifiedCartan.UnitaryPolynomialBounds
import ModifiedCartan.PolynomialLogMajorant
import ModifiedCartan.PointInitialCoarse
import ModifiedCartan.PointValueLower
import ModifiedCartan.JetAnchoredCompactness
import ModifiedCartan.PointInitialValue
import ModifiedCartan.PointSingularExponents
import ModifiedCartan.JetLogCompactness
import ModifiedCartan.PointJetUpper
import ModifiedCartan.ScaledPolynomialJets
import ModifiedCartan.SingularExponentLimits
import ModifiedCartan.JetLengthBounds
import ModifiedCartan.UnitaryNorm
import ModifiedCartan.ArbitraryRadiusConstruction
import ModifiedCartan.PolynomialNormLimit
import ModifiedCartan.ArbitraryRadiusData
import ModifiedCartan.LogMeasureTransfer
import ModifiedCartan.ReplacementNormProperties
import ModifiedCartan.PolynomialNormCompactness
import ModifiedCartan.VectorLogIntegrability
import ModifiedCartan.ExponentialLogComparison
import ModifiedCartan.EuclideanTriangle
import ModifiedCartan.OriginBound
import ModifiedCartan.GoodCenters
import ModifiedCartan.DiskMeanLimits
import ModifiedCartan.SubharmonicOrigin
import ModifiedCartan.ReplacementLogLimits
import ModifiedCartan.NormalizedRadialMean
import ModifiedCartan.NormalizedNormLimit
import ModifiedCartan.ReplacementSubsequence
import ModifiedCartan.EventualWronskianSum
import ModifiedCartan.LocalL1Max
import ModifiedCartan.LocalL1SmallError
import ModifiedCartan.FiniteLogMax
import ModifiedCartan.NormalizedNormMax
import ModifiedCartan.ArbitraryCoefficients
import ModifiedCartan.SubharmonicSup
import ModifiedCartan.LogLimitRepresentatives
import ModifiedCartan.ArbitraryEntireModels
import ModifiedCartan.GlobalMeasureModels
import ModifiedCartan.TwoPowerDiskBound
import ModifiedCartan.MonomialExtension
import ModifiedCartan.MonomialGerms
import ModifiedCartan.MeasureDilation
import ModifiedCartan.TwoPowerCauchy
import ModifiedCartan.ArbitraryLimitModels
import ModifiedCartan.ArbitraryCoefficientCompactness
import ModifiedCartan.TwoPowerExponents
import ModifiedCartan.ArbitraryScaleHypotheses
import ModifiedCartan.PowerNormalization
import ModifiedCartan.ArbitraryScaleWeight
import ModifiedCartan.SmallOrderClassification
import ModifiedCartan.ZeroOrderRamification
import ModifiedCartan.SystemPowerSequence
import ModifiedCartan.NormalizedMonomials
import ModifiedCartan.PolynomialNormalForm
import ModifiedCartan.AbsorptionConstants
import ModifiedCartan.ConvolutionAbsorption
import ModifiedCartan.PolynomialSequence
import ModifiedCartan.SystemDivisorMajorant
import ModifiedCartan.SmallOrderCoordinates
import ModifiedCartan.TranslatedCounting
import ModifiedCartan.NormalizedCharacteristic
import ModifiedCartan.TranslatedZeroCopies
import ModifiedCartan.TranslationWeightBound
import ModifiedCartan.WeightedZeroCounting
import ModifiedCartan.ExponentialGauge
import ModifiedCartan.NormalizedCoordinates
import ModifiedCartan.SmallOrderGauge
import ModifiedCartan.ShiftedCombinations
import ModifiedCartan.CurveOrderBasic
import ModifiedCartan.GaugedCoordinateBounds
import ModifiedCartan.CanonicalProductGrowth
import ModifiedCartan.CurveCoordinateCounting
import ModifiedCartan.EntirePoissonBound
import ModifiedCartan.GenusZeroGauge
import ModifiedCartan.GenusZeroMultiplicity
import ModifiedCartan.GenusZeroSubproduct
import ModifiedCartan.Convolution
import ModifiedCartan.GenusZeroZeros
import ModifiedCartan.EntireMajorant
import ModifiedCartan.GenusZeroProduct
import ModifiedCartan.WronskianCountingIntegralLimit
import ModifiedCartan.PolynomialIntegralMajorant
import ModifiedCartan.ExceptionalRadii
import ModifiedCartan.CountingPowerEnvelope
import ModifiedCartan.PolynomialRootLogCounting
import ModifiedCartan.WronskianUniform
import ModifiedCartan.PolynomialNormalizedMajorant
import ModifiedCartan.LogCountingLimit
import ModifiedCartan.RootConvolution
import ModifiedCartan.ZeroCopyLogCounting
import ModifiedCartan.RootMajorantProduct
import ModifiedCartan.IntegrableSum
import ModifiedCartan.WronskianReciprocalRoots
import ModifiedCartan.ReciprocalRoots
import ModifiedCartan.ReciprocalTailIntegral
import ModifiedCartan.TaylorWronskianGrowth
import ModifiedCartan.EntireCountGrowth
import ModifiedCartan.ZeroCopiesCount
import ModifiedCartan.SystemMaximum
import ModifiedCartan.EntireZeroCopies
import ModifiedCartan.EntireTaylorJets
import ModifiedCartan.RootKernel
import ModifiedCartan.EntireTaylorBounds
import ModifiedCartan.EntireOrder
import ModifiedCartan.RootKernelPrimitive
import ModifiedCartan.MaximumModulus
import ModifiedCartan.Envelope
import ModifiedCartan.EnvelopeConstantLimit
import ModifiedCartan.EnvelopeIntegration
import ModifiedCartan.EnvelopeKernel
import ModifiedCartan.Tonelli
import ModifiedCartan.EnvelopeRadii
import ModifiedCartan.Indices
import ModifiedCartan.PeakNonvanishing
import ModifiedCartan.AdmissibleInterval
import ModifiedCartan.PeakConstantSign
import ModifiedCartan.RepresentationMeanContradiction
import ModifiedCartan.RescaledZeroCoefficients
import ModifiedCartan.DiskCircleUpper
import ModifiedCartan.NormalizedLogUpper
import ModifiedCartan.NormalizedFundamentalODE
import ModifiedCartan.WeakGradientConstancy
import ModifiedCartan.LocalMeasureUniqueness
import ModifiedCartan.WeakZeroCutoff
import ModifiedCartan.WeakGradientSmoothing
import ModifiedCartan.FiniteLogCompactness
import ModifiedCartan.WeakGradientZeroTests
import ModifiedCartan.NormalizedLogCompactness
import ModifiedCartan.FiniteSubsequenceExtraction
import ModifiedCartan.AnalyticLogSubharmonic
import ModifiedCartan.AnalyticLogDiskMean
import ModifiedCartan.PeakScaleQuantization
import ModifiedCartan.PeakLimitScaleModels
import ModifiedCartan.PeakRescaling
import ModifiedCartan.AllScaleCauchyBounds
import ModifiedCartan.PeakCoefficientCompactness
import ModifiedCartan.MeasureDilationCompatibility
import ModifiedCartan.CurveCoordinateNormalization
import ModifiedCartan.EuclideanCoordinateNormalization
import ModifiedCartan.IsometryVectorTransport
import ModifiedCartan.CharacteristicPeaks
import ModifiedCartan.CharacteristicLogLower
import ModifiedCartan.PeakLogNormalization
import ModifiedCartan.ZeroJensenLowerBound
import ModifiedCartan.ScalarCurveBounds
import ModifiedCartan.CharacteristicIndices
import ModifiedCartan.PeakScaleBounds
import ModifiedCartan.CharacteristicZero
import ModifiedCartan.IndexOrderBounds
import ModifiedCartan.CharacteristicMonotone
import ModifiedCartan.OrdinaryGrowthOrders
import ModifiedCartan.UniformPowerLogBounds
import ModifiedCartan.PolyaPeaks
import ModifiedCartan.ApproximateGrowthPeaks
import ModifiedCartan.MultiplicativePeak
import ModifiedCartan.TiltedBlockGrowth
import ModifiedCartan.LogGrowthProfile
import ModifiedCartan.TiltedIntervalSup
import ModifiedCartan.StrongIndexPowerBounds
import ModifiedCartan.UniformPowerBounds
import ModifiedCartan.NeighborGrowth
import ModifiedCartan.GrowthPowerSymmetry
import ModifiedCartan.StrongGrowthIndices
import ModifiedCartan.GrowthMultiplierBounds
import ModifiedCartan.PolynomialReplacement
import ModifiedCartan.ReplacementRootData
import ModifiedCartan.ReplacementTaylorData
import ModifiedCartan.ReplacementCoefficientData
import ModifiedCartan.PolynomialApproximationLog
import ModifiedCartan.EventualCoefficientComparison
import ModifiedCartan.EventualTaylor
import ModifiedCartan.LogAreaJensen
import ModifiedCartan.SeparatingRadius
import ModifiedCartan.SmallPolynomialLog
import ModifiedCartan.RescaledRepresentation
import ModifiedCartan.RepresentationBound
import ModifiedCartan.CanonicalCompactness
import ModifiedCartan.HerglotzNormalization
import ModifiedCartan.BoundedWronskian
import ModifiedCartan.PoissonMajorant
import ModifiedCartan.MonicCircleMean
import ModifiedCartan.HarmonicBounds
import ModifiedCartan.QuotientWronskian
import ModifiedCartan.RepresentationAsymptotics
import ModifiedCartan.RepresentationCenter
import ModifiedCartan.CountingDilation
import ModifiedCartan.OpenDiskCounting
import ModifiedCartan.RescaledGauge
import ModifiedCartan.DivisorPolynomial
import ModifiedCartan.LocalCompactness
import ModifiedCartan.GaugeCoefficientAlgebra
import ModifiedCartan.CoefficientMeasurability
import ModifiedCartan.CanonicalJetSmallness
import ModifiedCartan.FiniteMeasureTuples
import ModifiedCartan.PolynomialGaugeSmallness
import ModifiedCartan.SmallRootPoleSums
import ModifiedCartan.LocalCoefficientCompactness
import ModifiedCartan.LocalCoefficientSplit
import ModifiedCartan.HolomorphicCompactness
import ModifiedCartan.MeasureLimitTransfer
import ModifiedCartan.SubsetProductBounds
import ModifiedCartan.PolynomialFamilyExpansion
import ModifiedCartan.LocalRootSeparation
import ModifiedCartan.RootDistanceSums
import ModifiedCartan.PolynomialRootCount
import ModifiedCartan.PolynomialApproximationCounting
import ModifiedCartan.LocalCramerComparison
import ModifiedCartan.LocalPolynomialApproximation
import ModifiedCartan.ExponentialJetApproximation
import ModifiedCartan.LocalJetDeterminantBounds
import ModifiedCartan.QuantitativeTaylor
import ModifiedCartan.ExponentialTaylorApproximation
import ModifiedCartan.MonicQuotientComparison
import ModifiedCartan.NegativeLogKernel
import ModifiedCartan.PolynomialNegativeArea
import ModifiedCartan.KPPolynomialCoefficientAction
import ModifiedCartan.KPParameterDifferentialCoefficients
import ModifiedCartan.ColumnMinorDifferentialEquation
import ModifiedCartan.SchubertColumnDifferentialEquation
import ModifiedCartan.SchubertDegreeInitialCoefficients
import ModifiedCartan.PolynomialCoefficientMinors
import ModifiedCartan.KPParameterCharacters
import ModifiedCartan.SchubertAdjugateReconstruction
import ModifiedCartan.KPParameterAdjugateReconstruction
import ModifiedCartan.KPJointInitialBasis
import ModifiedCartan.KPAdjugateMinorCharacters
import ModifiedCartan.KPRealJointActionExt
import ModifiedCartan.KPUniversalAdjugateIdentity
import ModifiedCartan.BetheAlgebraIdentification
import ModifiedCartan.KPCorrespondence
import ModifiedCartan.KPPolynomialParameters
import ModifiedCartan.KPParameterBetheAlgebra
import ModifiedCartan.PolynomialODEAdjugate
import ModifiedCartan.PolynomialODEAdjugateMap
import ModifiedCartan.PolynomialValueSpan
import ModifiedCartan.BetheAlgebra
import ModifiedCartan.PolynomialODEJetMatrix
import ModifiedCartan.PolynomialInitialBasisExistence
import ModifiedCartan.PolynomialInitialBasisCoordinates
import ModifiedCartan.PolynomialInitialValueBound
import ModifiedCartan.ReplacedMinorOrders
import ModifiedCartan.InitialPolynomialJetBounds
import ModifiedCartan.InitialPolynomialTaylorCoefficients
import ModifiedCartan.PolynomialInitialBasisMajorant
import ModifiedCartan.ColumnPartitionMinorOrders
import ModifiedCartan.ColumnMinorCramer
import ModifiedCartan.PolynomialCoefficientExpansion
import ModifiedCartan.PolynomialBasisReduction
import ModifiedCartan.PolynomialDegreeBasis
import ModifiedCartan.PolynomialSpaceSchubert
import ModifiedCartan.UniversalPolynomialMinors
import ModifiedCartan.KPAlphaExpectation
import ModifiedCartan.KPExpectationExpansion
import ModifiedCartan.KPSchubertUnitVector
import ModifiedCartan.KPSchubertConstantVector
import ModifiedCartan.SchubertMinorRatios
import ModifiedCartan.SchubertUniversalMinors
import ModifiedCartan.CommonEigenspaceAlgebra
import ModifiedCartan.KPCorrespondenceEigenspaces
import ModifiedCartan.SymmetricPolynomialSpecialization
import ModifiedCartan.KPSymmetricEquationTransfer
import ModifiedCartan.KPPolynomialEquationTransfer
import ModifiedCartan.FiniteKPJointEquation
import ModifiedCartan.KPEquationPolynomials
import ModifiedCartan.KPInverseCorrespondence
import ModifiedCartan.SchubertCoordinatePolynomials
import ModifiedCartan.MonicPolynomialParameters
import ModifiedCartan.KPWronskiMapDominance
import ModifiedCartan.JointEigenvectorDeterminants
import ModifiedCartan.KPParameterPermutation
import ModifiedCartan.SymmetricOrbitPolynomial
import ModifiedCartan.PolynomialMapDensity
import ModifiedCartan.SchubertChartSlots
import ModifiedCartan.SchubertChartPolynomials
import ModifiedCartan.SchubertChartSurjectivity
import ModifiedCartan.ClosedJointEigenprofiles
import ModifiedCartan.KPJointProfileClosed
import ModifiedCartan.PolynomialAlternantSeparation
import ModifiedCartan.SchubertCoordinateInjectivity
import ModifiedCartan.KPForwardCorrespondence
import ModifiedCartan.PolynomialPrimitives
import ModifiedCartan.MinorDimensionStep
import ModifiedCartan.SchubertDimensionStep
import ModifiedCartan.SchubertDimensionTransfer
import ModifiedCartan.KPJointSchubertSpace
import ModifiedCartan.SchubertMonicWronskian
import ModifiedCartan.KPJointWronskiFibre
import ModifiedCartan.PolynomialJetSupport
import ModifiedCartan.PolynomialJetDegreeProfile
import ModifiedCartan.PolynomialJetMatrixGauge
import ModifiedCartan.SchubertFrameReconstruction
import ModifiedCartan.KPJointValueNormalization
import ModifiedCartan.KPJointPolynomialTuple
import ModifiedCartan.AlternatingDualDeterminant
import ModifiedCartan.KPJointDecomposability
import ModifiedCartan.PolynomialAlternantMinors
import ModifiedCartan.PolynomialTensorFunctional
import ModifiedCartan.PolynomialTensorContraction
import ModifiedCartan.PartitionAlternatingDualForm
import ModifiedCartan.AlternatingDualDescent
import ModifiedCartan.KPJointCoefficientDimension
import ModifiedCartan.PolynomialLinearCoefficients
import ModifiedCartan.PolynomialCoefficientSpace
import ModifiedCartan.KPJointCoefficientSpace
import ModifiedCartan.MvPolynomialTranslationJets
import ModifiedCartan.TranslatedDifferentialKernel
import ModifiedCartan.OrderedPartitionExponents
import ModifiedCartan.PolynomialDeterminantCoefficients
import ModifiedCartan.AlternatingPolynomialExt
import ModifiedCartan.PolynomialAlternantTranslation
import ModifiedCartan.DividedAlternantTranslation
import ModifiedCartan.KPDividedPolynomialTranslation
import ModifiedCartan.KPJointShiftedContraction
import ModifiedCartan.DividedPowerAlternants
import ModifiedCartan.KPJointDividedContraction
import ModifiedCartan.PartitionAlternatingPolynomial
import ModifiedCartan.DividedPowerPolynomials
import ModifiedCartan.OrderedDeltaDeterminant
import ModifiedCartan.DividedPowerPartitionMinors
import ModifiedCartan.MvPolynomialCoefficientScale
import ModifiedCartan.MvDividedPowerNormalization
import ModifiedCartan.FiniteGroupLinearCoefficients
import ModifiedCartan.KPJointLinearValue
import ModifiedCartan.KPJointBernsteinResidue
import ModifiedCartan.KPJointAlternantContraction
import ModifiedCartan.PolynomialODEKernelBound
import ModifiedCartan.FrobeniusAlphabetEquiv
import ModifiedCartan.DescendingVandermonde
import ModifiedCartan.FiniteFinAlphabetShift
import ModifiedCartan.LaurentPolynomialCoefficients
import ModifiedCartan.FiniteBernsteinCoefficients
import ModifiedCartan.KPColumnLaurentExpansion
import ModifiedCartan.KPQuadraticFrobeniusExpansion
import ModifiedCartan.FrobeniusBernsteinCoefficients
import ModifiedCartan.KPFrobeniusBernsteinResidue
import ModifiedCartan.YoungHeightCollision
import ModifiedCartan.FrobeniusHeightVanishing
import ModifiedCartan.FrobeniusAlternantOrthogonality
import ModifiedCartan.FittingFrobeniusOrthogonality
import ModifiedCartan.FiniteFrobeniusSchur
import ModifiedCartan.FormalFrobeniusKernel
import ModifiedCartan.VandermondeAlternantMaps
import ModifiedCartan.PolynomialScalarSeries
import ModifiedCartan.AlternantCauchyExpansion
import ModifiedCartan.WeightedOrthogonalTriangularity
import ModifiedCartan.SeriesHomogenization
import ModifiedCartan.HomogenizedGeometricSeries
import ModifiedCartan.GeometricProductCoefficients
import ModifiedCartan.CauchyKernelCoefficients
import ModifiedCartan.SeparatedFrobeniusCauchy
import ModifiedCartan.HomogeneousSeriesCoefficients
import ModifiedCartan.AlternantHomogeneity
import ModifiedCartan.SingleVariableSeries
import ModifiedCartan.SeparateVariableProducts
import ModifiedCartan.FiniteGeometricSeries
import ModifiedCartan.FiniteCauchyRing
import ModifiedCartan.FiniteCauchySeries
import ModifiedCartan.FiniteAlternants
import ModifiedCartan.FrobeniusAlternantTriangularity
import ModifiedCartan.AlternantCoefficients
import ModifiedCartan.FiniteCauchyPivot
import ModifiedCartan.FiniteCauchyDeterminant
import ModifiedCartan.StaircaseWeights
import ModifiedCartan.FinitePartitionDegrees
import ModifiedCartan.DeterminantFirstPivot
import ModifiedCartan.CyclePolynomialCoefficients
import ModifiedCartan.FrobeniusCoefficientMultiplicity
import ModifiedCartan.YoungFrobeniusCoefficients
import ModifiedCartan.YoungColoringMinimum
import ModifiedCartan.ColoringColumnCancellation
import ModifiedCartan.YoungSpechtGenerator
import ModifiedCartan.YoungColoringVanishing
import ModifiedCartan.FrobeniusWeightVanishing
import ModifiedCartan.YoungRowDegrees
import ModifiedCartan.FrobeniusMinimalVanishing
import ModifiedCartan.FrobeniusSymmetry
import ModifiedCartan.FrobeniusHomogeneity
import ModifiedCartan.PolynomialFourierKernel
import ModifiedCartan.FixedColoringInverse
import ModifiedCartan.FiniteColoringAverage
import ModifiedCartan.FiniteFrobeniusCauchy
import ModifiedCartan.FinitePermutationCharacter
import ModifiedCartan.ColoringDegrees
import ModifiedCartan.WeightColoringRepresentation
import ModifiedCartan.WeightedBurnside
import ModifiedCartan.ColoringMultisets
import ModifiedCartan.ColoringOrbits
import ModifiedCartan.WeightedColoringBurnside
import ModifiedCartan.FiniteCycleIndex
import ModifiedCartan.FrobeniusSingleRow
import ModifiedCartan.FixedColoringProduct
import ModifiedCartan.GeneralMarkerEvaluation
import ModifiedCartan.EvaluatedQuadraticResidue
import ModifiedCartan.SubgroupFiniteSumCoefficient
import ModifiedCartan.SupportedRestrictionEquivalence
import ModifiedCartan.KPAlphaFrobeniusCoefficients
import ModifiedCartan.SizedPartitionsInSquare
import ModifiedCartan.KPAlphaBoundedFrobenius
import ModifiedCartan.SupportedPowerSumEvaluation
import ModifiedCartan.KPBetaFrobeniusIdentification
import ModifiedCartan.SquarefreeMarkerEvaluation
import ModifiedCartan.SupportedMarkerEvaluation
import ModifiedCartan.LaurentColumnCoefficient
import ModifiedCartan.KPColumnLaurentIdentification
import ModifiedCartan.ClassFunctionOperator
import ModifiedCartan.ClassFunctionScalarAction
import ModifiedCartan.ClassFunctionIsotypicAction
import ModifiedCartan.ClassFunctionSpechtExpansion
import ModifiedCartan.ClassFunctionRegularCoefficients
import ModifiedCartan.SpechtFourierExpansion
import ModifiedCartan.PolynomialSpechtFourier
import ModifiedCartan.FiniteCyclePolynomials
import ModifiedCartan.FiniteFrobeniusPolynomials
import ModifiedCartan.FiniteSubtypeSupports
import ModifiedCartan.SupportedDataRestriction
import ModifiedCartan.SupportedDataColoringTransport
import ModifiedCartan.ComplementMarkerClassification
import ModifiedCartan.AmbientFactorizationParameters
import ModifiedCartan.AmbientFactorizationLaurentSeries
import ModifiedCartan.AmbientFactorizationResidue
import ModifiedCartan.SupportedQuadraticMarkerCoefficients
import ModifiedCartan.SupportedQuadraticResidue
import ModifiedCartan.KPColumnSupportedExpansion
import ModifiedCartan.ZFactorizationParameters
import ModifiedCartan.ZFactorizationLaurentSeries
import ModifiedCartan.ZFactorizationResidue
import ModifiedCartan.ComplementMarkerDegrees
import ModifiedCartan.SupportedPowerSumQuadratic
import ModifiedCartan.SupportedPowerSumProduct
import ModifiedCartan.SupportedPowerSumResidue
import ModifiedCartan.ZCycleSupportFiniteness
import ModifiedCartan.ZFactorCardParity
import ModifiedCartan.RightZFactorPolynomial
import ModifiedCartan.RightZFactorLaurentSeries
import ModifiedCartan.ZSupportLaurentNormalization
import ModifiedCartan.ZComplementLaurentProduct
import ModifiedCartan.RightZFactorLaurentProduct
import ModifiedCartan.BernsteinScalarResidue
import ModifiedCartan.RightZFactorResidue
import ModifiedCartan.CycleUnionSignedColorings
import ModifiedCartan.CycleSubsetLaurentProduct
import ModifiedCartan.ZCycleSupportParameters
import ModifiedCartan.ZCycleSupportCard
import ModifiedCartan.PermutationCycleFibers
import ModifiedCartan.TransitivePermutationSign
import ModifiedCartan.CycleUnionCoordinates
import ModifiedCartan.CycleUnionSign
import ModifiedCartan.TransitiveSigmaColorings
import ModifiedCartan.CycleUnionPowerSums
import ModifiedCartan.CycleUnionSignTwist
import ModifiedCartan.FixedColoringDirectSum
import ModifiedCartan.ZFactorPowerSums
import ModifiedCartan.RightZFactorSignedSum
import ModifiedCartan.BlockInflationPowerSums
import ModifiedCartan.SignedBlockInflation
import ModifiedCartan.ZSupportCoordinates
import ModifiedCartan.SupportedPermutationRestrictions
import ModifiedCartan.ZFactorDirectSum
import ModifiedCartan.ZFactorSign
import ModifiedCartan.FixedColoringTransport
import ModifiedCartan.RightZFactorEndpoints
import ModifiedCartan.RightZFactorBijection
import ModifiedCartan.InvariantCycleSubsets
import ModifiedCartan.SigmaFiberPermutations
import ModifiedCartan.SigmaPermutationSign
import ModifiedCartan.BlockInflationColorings
import ModifiedCartan.BlockSuccessorClassification
import ModifiedCartan.ZPrefixPermutations
import ModifiedCartan.InvariantSupportedPermutations
import ModifiedCartan.ZConstructedRightFactor
import ModifiedCartan.RightZFactorExistence
import ModifiedCartan.ZSupportReconstruction
import ModifiedCartan.ZSupportParameters
import ModifiedCartan.InvariantCycleSets
import ModifiedCartan.BlockInflation
import ModifiedCartan.ZFactorSets
import ModifiedCartan.RightZFactors
import ModifiedCartan.ZStripLength
import ModifiedCartan.ZStripEmbedding
import ModifiedCartan.ZStripUnion
import ModifiedCartan.ZStripComplement
import ModifiedCartan.ZAdmissibleSets
import ModifiedCartan.ZStripPrefixLength
import ModifiedCartan.ZPrefixSets
import ModifiedCartan.LaurentVariableUnit
import ModifiedCartan.FiniteBernsteinLaurent
import ModifiedCartan.BernsteinCompositionSeries
import ModifiedCartan.BernsteinLaurentFactors
import ModifiedCartan.BernsteinFactorResidue
import ModifiedCartan.FactoredCompositionResidue
import ModifiedCartan.CompositionLaurentWeights
import ModifiedCartan.CompositionBoundaryResidue
import ModifiedCartan.NormalizedGeometricLaurent
import ModifiedCartan.NormalizedCompositionBoundary
import ModifiedCartan.NormalizedCompositionResidue
import ModifiedCartan.EmbeddingProductTransport
import ModifiedCartan.LaurentCompositionExpansion
import ModifiedCartan.ShiftedCompositionAlphabet
import ModifiedCartan.CompositionResidueTransport
import ModifiedCartan.ScaledMonomialEvaluation
import ModifiedCartan.BernsteinCompositionResidue
import ModifiedCartan.CompositionMarkerSubstitution
import ModifiedCartan.CompositionMarkerResidue
import ModifiedCartan.MonoidAlgebraCoefficientSwap
import ModifiedCartan.LaurentMarkerEquiv
import ModifiedCartan.MarkerAssignmentDegree
import ModifiedCartan.EmbeddingMarkerAssignment
import ModifiedCartan.MarkerAssignmentEquiv
import ModifiedCartan.MarkerAffineExpansion
import ModifiedCartan.MarkerEmbeddingCoefficients
import ModifiedCartan.MarkerSquarefreeJacobian
import ModifiedCartan.LaurentDerivative
import ModifiedCartan.LaurentDerivation
import ModifiedCartan.LaurentChangeVariableResidue
import ModifiedCartan.PositiveGeometricSum
import ModifiedCartan.FiniteCompositionSums
import ModifiedCartan.InjectiveGeometricProducts
import ModifiedCartan.FiniteAlphabetShift
import ModifiedCartan.FiniteBernstein
import ModifiedCartan.BernsteinScaledMonomials
import ModifiedCartan.BernsteinElementarySupport
import ModifiedCartan.ExtraColorEmbeddings
import ModifiedCartan.ExtraColorEquiv
import ModifiedCartan.InjectiveColorSums
import ModifiedCartan.ScaledMonomialExtraVariable
import ModifiedCartan.SignedColorStabilizer
import ModifiedCartan.SignedFixedColorings
import ModifiedCartan.CycleColorings
import ModifiedCartan.CycleWeightedPowers
import ModifiedCartan.ScaledMonomialPowerSums
import ModifiedCartan.CyclicSubalgebra
import ModifiedCartan.KPSpechtAlgebra
import ModifiedCartan.KPDeformedAlgebra
import ModifiedCartan.KPRealSymmetric
import ModifiedCartan.KPRealJointDecomposition
import ModifiedCartan.ColumnPartitions
import ModifiedCartan.TwoLetterPermutations
import ModifiedCartan.KPColumnTwoAlpha
import ModifiedCartan.PairSubsetSum
import ModifiedCartan.KPRootWeights
import ModifiedCartan.KPColumnTwoBeta
import ModifiedCartan.KPGaudinMembership
import ModifiedCartan.KPGeneratedCyclicity
import ModifiedCartan.KPJointWronskian
import ModifiedCartan.ScalarActionCharacter
import ModifiedCartan.KPJointCharacter
import ModifiedCartan.KPFullCharacterAction
import ModifiedCartan.KPBetaFullSize
import ModifiedCartan.CharacterPositive
import ModifiedCartan.KPAlphaPositive
import ModifiedCartan.KPTranslatedVanishing
import ModifiedCartan.KPSpechtSupport
import ModifiedCartan.CommonEigenvectors
import ModifiedCartan.KPJointEigenspace
import ModifiedCartan.ScalarActionAdjoin
import ModifiedCartan.KPJointEigenvalues
import ModifiedCartan.KPCurvePolynomial
import ModifiedCartan.KPCurveMatrix
import ModifiedCartan.SpechtKPCommutation
import ModifiedCartan.IsotypicAnnihilator
import ModifiedCartan.SpechtAlgebraFaithful
import ModifiedCartan.KPBetaCommutation
import ModifiedCartan.KPGeneratedCommutative
import ModifiedCartan.GaudinDegenerationElement
import ModifiedCartan.GaudinCyclicity
import ModifiedCartan.KPBetaDeformedCommutation
import ModifiedCartan.PolynomialInverseContinuation
import ModifiedCartan.GaudinDegenerationScalar
import ModifiedCartan.GaudinDegenerationIdentity
import ModifiedCartan.MatrixCyclic
import ModifiedCartan.MatrixCyclicOpen
import ModifiedCartan.JucysMurphyBasisStep
import ModifiedCartan.JucysMurphyBasisZero
import ModifiedCartan.JucysMurphyEigenbasis
import ModifiedCartan.JucysMurphyCyclicity
import ModifiedCartan.JucysMurphyElements
import ModifiedCartan.IntertwinerAlgebraAction
import ModifiedCartan.JucysMurphyRestriction
import ModifiedCartan.LastLetterSpectrum
import ModifiedCartan.EigenblockBasis
import ModifiedCartan.SpechtCornerDirectSum
import ModifiedCartan.SubsetRepresentationOperators
import ModifiedCartan.SpechtCornerStarEigenvalue
import ModifiedCartan.SimpleEigenbasisCyclic
import ModifiedCartan.FiniteJointSpectrumSeparation
import ModifiedCartan.JointEigenbasisCyclic
import ModifiedCartan.EigenblockSum
import ModifiedCartan.SymmetricPairErasureModule
import ModifiedCartan.TotalTranspositionDeletion
import ModifiedCartan.CharacterProjectorRank
import ModifiedCartan.MultiplicityOneIsotypic
import ModifiedCartan.SpechtRestrictionMultiplicity
import ModifiedCartan.CyclicCentralizer
import ModifiedCartan.TotalTranspositionReindex
import ModifiedCartan.YoungBoxFiberCounts
import ModifiedCartan.SymmetricPairDeletion
import ModifiedCartan.YoungTranspositionCorner
import ModifiedCartan.YoungSwapCoefficient
import ModifiedCartan.TotalTranspositionElement
import ModifiedCartan.TotalTranspositionOperator
import ModifiedCartan.YoungTranspositionScalar
import ModifiedCartan.AllSubsetInsertion
import ModifiedCartan.KPGaudinReduction
import ModifiedCartan.KPGaudinCommutation
import ModifiedCartan.FiniteSubsetSwaps
import ModifiedCartan.PermutationStar
import ModifiedCartan.KPAlphaEraseCommutator
import ModifiedCartan.KPSubsetWeights
import ModifiedCartan.FiniteInvolutionSum
import ModifiedCartan.FinsetSwapEquiv
import ModifiedCartan.KPTranspositionCommutator
import ModifiedCartan.KPGeneratedShift
import ModifiedCartan.SupportedPermutationImages
import ModifiedCartan.KPAlphaConjugation
import ModifiedCartan.KPCoefficientTableaux
import ModifiedCartan.KPCoefficientTranslation
import ModifiedCartan.KPTranslation
import ModifiedCartan.SizedSubsetInsertion
import ModifiedCartan.KPPolynomialCoefficients
import ModifiedCartan.KPCoefficientDerivative
import ModifiedCartan.KPCoefficientDegree
import ModifiedCartan.LegalMinorRowCovers
import ModifiedCartan.KPCoefficientGrowthPaths
import ModifiedCartan.BoundedPartitionSquare
import ModifiedCartan.KPAlphaCoefficients
import ModifiedCartan.KPAlphaFullInduction
import ModifiedCartan.NestedPermutationErasure
import ModifiedCartan.KPSubsetInduction
import ModifiedCartan.FixedPointPermutationSums
import ModifiedCartan.InducedSpechtClassFunction
import ModifiedCartan.SpechtRestrictionPairing
import ModifiedCartan.SpechtInductionPairing
import ModifiedCartan.SpechtInductionCharacter
import ModifiedCartan.ClassScalarIsotypic
import ModifiedCartan.SpechtClassExpansion
import ModifiedCartan.SpechtIrreducibleExhaustion
import ModifiedCartan.CharacterProjectorOrthogonal
import ModifiedCartan.RegularCharacterTrace
import ModifiedCartan.FiniteOrthogonalProjectors
import ModifiedCartan.SpechtRegularCompleteness
import ModifiedCartan.SpechtProjectorCompleteness
import ModifiedCartan.ClassWeightedOperator
import ModifiedCartan.RankedYoungCoverEquivs
import ModifiedCartan.WeightedYoungDifferential
import ModifiedCartan.RankedTableauDimension
import ModifiedCartan.UpwardTableauDimension
import ModifiedCartan.SpechtDimensionSquareSum
import ModifiedCartan.YoungPredecessorCount
import ModifiedCartan.PartitionCommonCoverGeometry
import ModifiedCartan.YoungLatticeDifferential
import ModifiedCartan.FiniteCommonNeighborSums
import ModifiedCartan.PartitionCovers
import ModifiedCartan.SizedYoungDiagrams
import ModifiedCartan.YoungCornerRowDrops
import ModifiedCartan.AddableRowsCornerEquiv
import ModifiedCartan.PartitionCoverAddition
import ModifiedCartan.YoungSuccessorCount
import ModifiedCartan.SpechtCharacterPairingStep
import ModifiedCartan.SpechtRestrictedCharacterSums
import ModifiedCartan.SpechtPredecessorsFromCharacters
import ModifiedCartan.TwoBoxSpechtDistinction
import ModifiedCartan.SpechtShapeReconstruction
import ModifiedCartan.SpechtDistinctCharacters
import ModifiedCartan.CyclicSpechtCharacters
import ModifiedCartan.RowColumnSpechtCharacters
import ModifiedCartan.RowColumnFiniteCharacters
import ModifiedCartan.CornerPredecessors
import ModifiedCartan.CornerRemovalGeometry
import ModifiedCartan.PartitionPredecessorReconstruction
import ModifiedCartan.SpechtFiniteAlphabetRepresentation
import ModifiedCartan.KPOperators
import ModifiedCartan.SpechtFiniteAlphabetBranching
import ModifiedCartan.CornerRemainingAlphabet
import ModifiedCartan.SpechtBranchingCommonAlphabet
import ModifiedCartan.FixedPointDeletion
import ModifiedCartan.SpechtCharacterBranching
import ModifiedCartan.SpechtCharacterLabels
import ModifiedCartan.SpechtRowCharacters
import ModifiedCartan.RowFiltrationCharacterRelabel
import ModifiedCartan.CornerCharacterContributions
import ModifiedCartan.SpechtBranchingEquiv
import ModifiedCartan.TraceSurjectiveKernel
import ModifiedCartan.NestedSubmoduleTrace
import ModifiedCartan.SpechtBranchingMap
import ModifiedCartan.SpechtFiltrationRanks
import ModifiedCartan.DeletionImageDimension
import ModifiedCartan.CornerDimensionSum
import ModifiedCartan.BranchingImageEquality
import ModifiedCartan.TabloidDeletionLinear
import ModifiedCartan.RemovalSigns
import ModifiedCartan.PolytabloidDeletion
import ModifiedCartan.DeletionImageSpecht
import ModifiedCartan.RowFiltrationRelabel
import ModifiedCartan.SubmoduleImageRankNullity
import ModifiedCartan.RemovedPermutations
import ModifiedCartan.InsertedTabloids
import ModifiedCartan.LastRowSupport
import ModifiedCartan.TabloidRowCutoff
import ModifiedCartan.SpechtRowFiltration
import ModifiedCartan.PartitionCorners
import ModifiedCartan.TableauLastBox
import ModifiedCartan.RemovedBoxes
import ModifiedCartan.TableauDeleteLast
import ModifiedCartan.TableauExtendLast
import ModifiedCartan.CornerTableauEquiv
import ModifiedCartan.CornerTableauCount
import ModifiedCartan.FillingTabloids
import ModifiedCartan.StrictPermutationWeight
import ModifiedCartan.ColumnPermutations
import ModifiedCartan.ColumnRearrangement
import ModifiedCartan.FillingCoefficients
import ModifiedCartan.YoungTabloidWeight
import ModifiedCartan.LeadingCoefficientIndependence
import ModifiedCartan.StandardPolytabloidBasis
import ModifiedCartan.SpechtCharacterProjection
import ModifiedCartan.FiniteSetExchange
import ModifiedCartan.GarnirSeparation
import ModifiedCartan.GarnirMixing
import ModifiedCartan.TwoBlockWeightedSum
import ModifiedCartan.YoungFillingWeight
import ModifiedCartan.StandardPolytabloidSpanning
import ModifiedCartan.GarnirRelation
import ModifiedCartan.SubsetAlternatingCancellation
import ModifiedCartan.GarnirBelt
import ModifiedCartan.GarnirAlternation
import ModifiedCartan.SubgroupAlternation
import ModifiedCartan.SupportedPermutations
import ModifiedCartan.ColumnStandardSpanning
import ModifiedCartan.ColumnSorting
import ModifiedCartan.SortedColumnLabels
import ModifiedCartan.FillingPolytabloids
import ModifiedCartan.YoungFillings
import ModifiedCartan.SpechtRepresentation
import ModifiedCartan.RepresentationReindex
import ModifiedCartan.YoungSpechtIrreducible
import ModifiedCartan.YoungSpechtSubmoduleTheorem
import ModifiedCartan.YoungAlternatingHermitian
import ModifiedCartan.YoungAlternatingRange
import ModifiedCartan.YoungTabloidInnerProduct
import ModifiedCartan.YoungColumnOrbit
import ModifiedCartan.YoungAlternatingOperator
import ModifiedCartan.YoungTabloidCancellation
import ModifiedCartan.YoungColumnMinimum
import ModifiedCartan.YoungColumns
import ModifiedCartan.FiniteRowMinimum
import ModifiedCartan.YoungSpechtModule
import ModifiedCartan.YoungTabloidRows
import ModifiedCartan.YoungColumnAlternation
import ModifiedCartan.YoungPolytabloid
import ModifiedCartan.YoungPermutationSubgroups
import ModifiedCartan.SymmetricCharacterProjection
import ModifiedCartan.CharacterProjectionBound
import ModifiedCartan.IsotypicCopies
import ModifiedCartan.CharacterOrthogonalProjection
import ModifiedCartan.CharacterOrthogonalInvariant
import ModifiedCartan.CharacterProjectorRange
import ModifiedCartan.CharacterIrreducibleImages
import ModifiedCartan.GroupSubmoduleIntertwiners
import ModifiedCartan.CharacterProjectorFixed
import ModifiedCartan.CharacterSimpleGeneration
import ModifiedCartan.CharacterProjectorBasic
import ModifiedCartan.CharacterScalarAction
import ModifiedCartan.CentralCharacterOperator
import ModifiedCartan.PluckerTranslation
import ModifiedCartan.SchubertCoordinates
import ModifiedCartan.SchubertWronskianDegree
import ModifiedCartan.PolynomialMinorBasisChange
import ModifiedCartan.NormalizedMinorTranslation
import ModifiedCartan.MinorTranslation
import ModifiedCartan.MinorDerivativeSubpartitions
import ModifiedCartan.TableauCountPositive
import ModifiedCartan.PartitionTopMinor
import ModifiedCartan.PartitionMinorDegree
import ModifiedCartan.PartitionMinorSupport
import ModifiedCartan.MinorDerivativeTableaux
import ModifiedCartan.SortedMinorOrders
import ModifiedCartan.GrowthCountTableaux
import ModifiedCartan.MinorGrowthCount
import ModifiedCartan.SkewGrowthRows
import ModifiedCartan.TableauCountRecurrence
import ModifiedCartan.SkewAdditions
import ModifiedCartan.TableauFirstBoxEquiv
import ModifiedCartan.TableauPrepend
import ModifiedCartan.TableauTail
import ModifiedCartan.SkewBoxInsertion
import ModifiedCartan.GrowthPathTableaux
import ModifiedCartan.GrowthPathBoxes
import ModifiedCartan.TableauPrefixSteps
import ModifiedCartan.TableauPrefixes
import ModifiedCartan.MinorGrowthPaths
import ModifiedCartan.TableauFirstBox
import ModifiedCartan.SkewTableaux
import ModifiedCartan.FinitePartitions
import ModifiedCartan.PartitionMinorDerivative
import ModifiedCartan.PartitionBoxes
import ModifiedCartan.PolynomialMinors
import FewInflection
import ModifiedCartan.NormComparison
import ModifiedCartan.Targets
import ModifiedCartan.Counting
import ModifiedCartan.CountingIntegral
import ModifiedCartan.EuclideanJensen
import ModifiedCartan.FundamentalOperator
import ModifiedCartan.CanonicalCoefficients
import ModifiedCartan.CanonicalGauge
import ModifiedCartan.CanonicalDilation
import ModifiedCartan.CanonicalTheorem
import ModifiedCartan.WronskianNontrivial
import ModifiedCartan.LocalConvergence
import ModifiedCartan.CauchyKernel
import ModifiedCartan.LogKernel
import ModifiedCartan.LogLp
import ModifiedCartan.CauchyTruncation
import ModifiedCartan.LocalSubsequence
import ModifiedCartan.LogDerivativeLp
import ModifiedCartan.AnalyticLogLp
import ModifiedCartan.MeasureCauchy
import ModifiedCartan.CauchyRegularization
import ModifiedCartan.CauchyWeak
import ModifiedCartan.LogRegularization
import ModifiedCartan.LogWeak
import ModifiedCartan.LogKernelDerivative
import ModifiedCartan.LogPotentialDerivative
import ModifiedCartan.LogPotentialLp
import ModifiedCartan.WeakGradient
import ModifiedCartan.LogLaplacian
import ModifiedCartan.HarmonicWeak
import ModifiedCartan.LogRiesz
import ModifiedCartan.LocalizedMeasures
import ModifiedCartan.MeasureSubsequence
import ModifiedCartan.LocalizedRepresentation
import ModifiedCartan.HarmonicRadialMean
import ModifiedCartan.RadialKernel
import ModifiedCartan.HarmonicSmoothing
import ModifiedCartan.LocalConvergenceAlgebra
import ModifiedCartan.HarmonicInterior
import ModifiedCartan.LogLimitRepresentation
import ModifiedCartan.WeakGradientCalculus
import ModifiedCartan.LogLimitSobolev
import ModifiedCartan.WeakGradientUnique
import ModifiedCartan.HarmonicHigher
import ModifiedCartan.LocalLogHypotheses
import ModifiedCartan.WeakGradientLocality
import ModifiedCartan.SobolevLocality
import ModifiedCartan.LogLimitRegularity
import ModifiedCartan.UniformLocalLp
import ModifiedCartan.ClassicalWeakGradient
import ModifiedCartan.AnalyticWeakGradient
import ModifiedCartan.GradientConvergence
import ModifiedCartan.LocalLpGluing
import ModifiedCartan.LogDerivSubsequence
import ModifiedCartan.FirstLogDerivLimit
import ModifiedCartan.MeasureConvergenceAlgebra
import ModifiedCartan.SingularPowerEstimate
import ModifiedCartan.HarmonicComplexDerivatives
import ModifiedCartan.ZeroFractionalMass
import ModifiedCartan.FiniteCauchyDerivatives
import ModifiedCartan.FractionalConvergence
import ModifiedCartan.SingularLogDerivative
import ModifiedCartan.MeasureConvergenceLocality
import ModifiedCartan.HigherLogDerivSubsequence
import ModifiedCartan.HigherLogDerivLimit
import ModifiedCartan.MeasureFiniteAlgebra
import ModifiedCartan.LogDerivativePartitions
import ModifiedCartan.LogDerivativeLimit
import ModifiedCartan.ExtendedLogConvergence
import ModifiedCartan.WronskianDeterminant
import ModifiedCartan.ScaledLogMeasure
import ModifiedCartan.WronskianLogInequality
import ModifiedCartan.WronskianSumLimit
import ModifiedCartan.ComponentSandwich
import ModifiedCartan.SubharmonicBasic
import ModifiedCartan.SubharmonicLocalIntegrability
import ModifiedCartan.SubharmonicMean
import ModifiedCartan.SubharmonicUpperBounds
import ModifiedCartan.SubharmonicRepresentative
import ModifiedCartan.SubharmonicL1Bounds
import ModifiedCartan.SubharmonicAnchorSubsequence
import ModifiedCartan.SubharmonicL1Propagation
import ModifiedCartan.SubharmonicL1Alternative
import ModifiedCartan.DiskAverages
import ModifiedCartan.DiskKernel
import ModifiedCartan.DiskAverageDuality
import ModifiedCartan.DiskAverageApproximation
import ModifiedCartan.WeightedAveragingError
import ModifiedCartan.MovingDiskIntegrals
import ModifiedCartan.LocalAveragingError
import ModifiedCartan.SubharmonicAveragingOrder
import ModifiedCartan.LipschitzCutoff
import ModifiedCartan.SubharmonicAveragingApproximation
import ModifiedCartan.UniformLipschitzCompactness
import ModifiedCartan.ApproximationCompactness
import ModifiedCartan.L1CompactnessMetric
import ModifiedCartan.AveragedL1Compactness
import ModifiedCartan.SubharmonicDiskCompactness
import ModifiedCartan.L1SubsequenceCompactness
import ModifiedCartan.LocalL1Limits
import ModifiedCartan.SubharmonicLocalCompactness
import ModifiedCartan.DiskNeighborhoods
import ModifiedCartan.DiskAverageContinuity
import ModifiedCartan.LocalDiskAverageContinuity
import ModifiedCartan.DiskAverageDifferentiation
import ModifiedCartan.SubmeanEnvelope
import ModifiedCartan.SubharmonicLimitMeans
import ModifiedCartan.SubharmonicMeanCriterion
import ModifiedCartan.SubmeanEnvelopeRepresentative
import ModifiedCartan.SubharmonicLimitRepresentative
import ModifiedCartan.SubharmonicCompactness

/-!
Entry point for the zero-external-assumptions development of the submitted paper.
The inherited modules are proved building blocks, not a proof of the whole paper.
See FORMALIZATION_MAP.md for the precise completion boundary.
-/
































































































































































































































