import FewInflection.FundamentalLimits

open scoped BigOperators Topology

namespace FewInflection
noncomputable section

/-! The exact differential recursion behind the normalized derivative
expansion.  It is proved pointwise away from a zero of the denominator, so no
almost-everywhere convention is hidden in the statement. -/
theorem normalized_iteratedDeriv_recursion
    {h : ℂ → ℂ} (hh : Differentiable ℂ h)
    {k : ℕ} {z : ℂ} (hz : h z ≠ 0) :
    deriv (fun w => iteratedDeriv k h w / h w) z +
        (deriv h z / h z) * (iteratedDeriv k h z / h z) =
      iteratedDeriv (k + 1) h z / h z := by
  have hcont : ContDiff ℂ (k + 1) h := hh.contDiff
  have hd : DifferentiableAt ℂ (iteratedDeriv k h) z :=
    (hcont.differentiable_iteratedDeriv' k).differentiableAt
  have hnum : HasDerivAt (iteratedDeriv k h)
      (iteratedDeriv (k + 1) h z) z := by
    have hd' := hd.hasDerivAt
    simpa only [iteratedDeriv_succ] using hd'
  have hden : HasDerivAt h (deriv h z) z := hh.differentiableAt.hasDerivAt
  have hdiv := hnum.div hden hz
  change deriv (iteratedDeriv k h / h) z +
      (deriv h z / h z) * (iteratedDeriv k h z / h z) =
      iteratedDeriv (k + 1) h z / h z
  rw [hdiv.deriv]
  field_simp [hz]
  ring

/-! In the zero-free case the preceding recursion is the usual first step of
the differential-polynomial expansion in logarithmic derivatives. -/
theorem normalized_secondDeriv_eq_deriv_logDeriv_add_sq
    {h : ℂ → ℂ} (hh : Differentiable ℂ h)
    (hzero : ∀ w, h w ≠ 0) (z : ℂ) :
    iteratedDeriv 2 h z / h z =
      deriv (logDeriv h) z + (logDeriv h z) ^ 2 := by
  have hr := normalized_iteratedDeriv_recursion hh (k := 1) (hzero z)
  have hfun : (fun w => iteratedDeriv 1 h w / h w) = logDeriv h := by
    funext w
    simp [iteratedDeriv_one, logDeriv_apply]
  rw [hfun] at hr
  rw [congrFun hfun z] at hr
  have hlog : logDeriv h z = deriv h z / h z := by
    simp [logDeriv_apply (f := h) (x := z)]
  rw [hlog] at hr
  have hsq : (deriv h z / h z) * (deriv h z / h z) =
      (logDeriv h z) ^ 2 := by
    simp [logDeriv_apply (f := h) (x := z), pow_two]
  have hr' : deriv (logDeriv h) z +
      (deriv h z / h z) * (deriv h z / h z) =
      iteratedDeriv 2 h z / h z := by
    simpa using hr
  rw [hsq] at hr'
  simpa using hr'.symm

/-! A recursive differential-polynomial form of the higher normalized
derivatives.  The recursion is intentionally expressed at the level of
functions: its coefficients are generated by actual analytic derivatives,
and the theorem below identifies it with `h^(k)/h` for a zero-free function. -/
def normalizedDifferentialPolynomial (L : ℂ → ℂ) : ℕ → ℂ → ℂ
  | 0 => fun _ => 1
  | k + 1 => fun z =>
      deriv (normalizedDifferentialPolynomial L k) z +
        L z * normalizedDifferentialPolynomial L k z

@[simp] theorem normalizedDifferentialPolynomial_zero (L : ℂ → ℂ) :
    normalizedDifferentialPolynomial L 0 = fun _ => 1 := rfl

@[simp] theorem normalizedDifferentialPolynomial_one (L : ℂ → ℂ) :
    normalizedDifferentialPolynomial L 1 = L := by
  funext z
  simp [normalizedDifferentialPolynomial]

@[simp] theorem normalizedDifferentialPolynomial_two (L : ℂ → ℂ) :
    normalizedDifferentialPolynomial L 2 =
      fun z => deriv L z + L z ^ 2 := by
  funext z
  simp [normalizedDifferentialPolynomial, pow_two]

theorem normalized_iteratedDeriv_eq_differentialPolynomial
    {h : ℂ → ℂ} (hh : Differentiable ℂ h)
    (hzero : ∀ w, h w ≠ 0) (k : ℕ) :
    (fun z => iteratedDeriv k h z / h z) =
      normalizedDifferentialPolynomial (logDeriv h) k := by
  induction k with
  | zero =>
      funext z
      simp [normalizedDifferentialPolynomial, hzero z]
  | succ k ih =>
      funext z
      have hr := normalized_iteratedDeriv_recursion hh
        (k := k) (z := z) (hzero z)
      rw [ih, congrFun ih z] at hr
      have hlog : logDeriv h z = deriv h z / h z := by
        simp [logDeriv_apply]
      simp only [normalizedDifferentialPolynomial]
      rw [hlog]
      exact hr.symm

end
end FewInflection
